#!/usr/bin/env python3
"""Post-fly fallback: create a GitHub Discussion if the LLM didn't.

Reads session.json after a fly session. If create_discussion was never
called (e.g., rate limit, turn budget exhaustion), this script creates
a discussion from the session summary so Oskar always gets notified.

Usage:
    python .perch/post_fly.py          # reads session.json in cwd
    python .perch/post_fly.py --dry-run  # print what would be posted
"""

import json
import os
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path


REPO_ID = "R_kgDOQEB8Eg"
FLIGHT_LOG_CATEGORY_ID = "DIC_kwDOQEB8Es4C31s9"
GRAPHQL_URL = "https://api.github.com/graphql"


def was_discussion_created(record: dict) -> bool:
    """Check if create_discussion was successfully called during the session."""
    for tc in record.get("tool_calls", []):
        if tc.get("name") == "create_discussion":
            # If it was called and didn't produce an error-length output, assume success
            # (successful responses are ~60 chars like "Discussion #N created: url")
            if tc.get("output_chars", 0) > 20:
                return True
    return False


def build_discussion_body(record: dict) -> str:
    """Build a discussion body from the session record."""
    task = record.get("routed_task") or record.get("task", "fly")
    model = record.get("model", "unknown")
    turns = record.get("turns", 0)
    cost = record.get("estimated_cost_usd", 0)
    summary = record.get("summary", "No summary available.")
    errors = record.get("errors", [])
    started = record.get("started_at", "")
    ended = record.get("ended_at", "")

    body = f"""## Fly Session Summary

{summary}

---

*Auto-generated by post_fly fallback — the LLM session ended before calling `create_discussion`.*

| Field | Value |
|-------|-------|
| Task | {task} |
| Model | {model} |
| Turns | {turns} |
| Cost | ${cost:.4f} |
| Started | {started} |
| Ended | {ended} |
| Errors | {len(errors)} |
"""

    if errors:
        body += "\n### Errors\n\n"
        for e in errors:
            # Truncate long error messages
            short = e[:200] + "..." if len(e) > 200 else e
            body += f"- `{short}`\n"

    return body


def build_discussion_title(record: dict) -> str:
    """Generate a title from the summary's first sentence."""
    summary = record.get("summary", "")
    # Take first sentence (up to period, question mark, or newline)
    for delim in [".", "?", "\n"]:
        idx = summary.find(delim)
        if idx > 0:
            candidate = summary[:idx].strip()
            if 10 < len(candidate) < 120:
                return candidate
            break

    # Fallback to date-based title
    date = record.get("started_at", "")[:10] or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return f"Fly exploration — {date}"


def create_discussion(title: str, body: str, token: str, dry_run: bool = False) -> str:
    """Create a GitHub Discussion via GraphQL API."""
    if dry_run:
        print(f"DRY RUN — would create discussion:")
        print(f"  Title: {title}")
        print(f"  Body length: {len(body)} chars")
        print(f"  Body preview: {body[:300]}...")
        return "dry-run"

    mutation = """mutation($input: CreateDiscussionInput!) {
      createDiscussion(input: $input) {
        discussion { id number url }
      }
    }"""

    variables = {
        "input": {
            "repositoryId": REPO_ID,
            "categoryId": FLIGHT_LOG_CATEGORY_ID,
            "title": title,
            "body": body,
        }
    }

    payload = json.dumps({"query": mutation, "variables": variables}).encode()
    req = urllib.request.Request(
        GRAPHQL_URL,
        data=payload,
        headers={
            "Authorization": f"bearer {token}",
            "Content-Type": "application/json",
        },
    )

    resp = urllib.request.urlopen(req)
    data = json.loads(resp.read())

    if "errors" in data:
        print(f"GraphQL errors: {data['errors']}", file=sys.stderr)
        return ""

    disc = data["data"]["createDiscussion"]["discussion"]
    url = disc["url"]
    print(f"Discussion #{disc['number']} created: {url}")
    return url


def main():
    dry_run = "--dry-run" in sys.argv

    session_path = Path("session.json")
    if not session_path.exists():
        print("No session.json found, skipping.", file=sys.stderr)
        sys.exit(0)

    record = json.loads(session_path.read_text())

    # Only run for fly sessions (direct or dispatched)
    task = record.get("task", "")
    routed_task = record.get("routed_task", "")
    if task != "fly" and routed_task != "fly":
        print(f"Task is '{task}' (routed: '{routed_task}'), not fly. Skipping.")
        sys.exit(0)

    if was_discussion_created(record):
        print("Discussion was already created during the session. Skipping.")
        sys.exit(0)

    # Discussion not created — do it now
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if not token and not dry_run:
        print("No GitHub token available. Cannot create discussion.", file=sys.stderr)
        sys.exit(1)

    title = build_discussion_title(record)
    body = build_discussion_body(record)
    create_discussion(title, body, token, dry_run=dry_run)


if __name__ == "__main__":
    main()
